feat：fix reentrancy contract code
Dapp-Learning-DAO/Dapp-Learning pull request #1209
Opened 2024-10-26 05:12 UTC by luna2163

When studying the contract security the dao case, I found that the contract code had some problems

and the README document was a bit rough, so I optimized it.

Finally, I still thank dapp-learning for its excellent case, **salute 🫡**

2024-10-31 10:20 UTC, 0x-stan requested changes
看起来没有实质性的修改，另外README有中文和英文版，请不要将中文内容放入英文README

2024-11-02 03:13 UTC, luna2163 commented
> 看起来没有实质性的修改，另外README有中文和英文版，请不要将中文内容放入英文README

"Sorry for the mixed language in the README. As mentioned before, the documentation and code are a bit rough. For example, the `Malicious` contract was declared three times, so I've optimized it."

2024-11-04 11:46 UTC, 0x-stan approved these changes

2024-11-04 12:28 UTC, jasonandjay approved these changes

2024-11-04 12:28 UTC, merged