updated task 33 readme
Dapp-Learning-DAO/Dapp-Learning pull request #527
Opened 2021-12-22 05:03 UTC by MiaoNan

Add more detailed description about pool token and two reference links.

2021-12-22 07:43 UTC, maroonstar requested changes

2021-12-22 07:43 UTC, maroonstar commented on basic/33-pooltogether/README.md
> +Discord: https://t.co/qAQbalbLER
Please remove discord and tg links

2021-12-23 04:41 UTC, jhfnetboy commented on basic/33-pooltogether/README.md
> +Discord: https://t.co/qAQbalbLER
no ads

2021-12-23 08:12 UTC, liberhe approved these changes

2021-12-24 02:56 UTC, Loverush approved these changes

2021-12-24 04:47 UTC, jhfnetboy approved these changes
got it~

2021-12-25 06:18 UTC, maroonstar approved these changes

2021-12-25 06:19 UTC, merged