Update task 14 chainlink
Dapp-Learning-DAO/Dapp-Learning pull request #530
Opened 2021-12-23 03:58 UTC by maroonstar

- add Chainlink VRF usage
- update chainlink node lib
- add ethers.js usage

2021-12-23 04:40 UTC, jhfnetboy submitted a review, later dismissed
I have't built any app with chainlink yet. Thx~!

2021-12-23 05:24 UTC, luckyyang commented on basic/14-chainlink-price-feed/README.md
> +Chainlink VRF 可验证随机函数， 是一种可证明公平且可验证呃随机性来源。作为防篡改随机数生成器，为依赖不可预测结果的任何应用程序构建构建智能合约。
公平且可验证~~呃~~随机性来源

2021-12-23 05:30 UTC, luckyyang requested changes
A typo need to be fixed

2021-12-24 02:55 UTC, Loverush submitted a review, later dismissed

2021-12-24 04:38 UTC, maroonstar commented on basic/14-chainlink-price-feed/README.md
> +Chainlink VRF 可验证随机函数， 是一种可证明公平且可验证呃随机性来源。作为防篡改随机数生成器，为依赖不可预测结果的任何应用程序构建构建智能合约。
fixed

2021-12-24 04:40 UTC, maroonstar commented
update: modify RandomNumberConsumer conract with adding two events; listen on event in test case file; fixed typo;

2021-12-24 04:46 UTC, jhfnetboy approved these changes
again~

2021-12-26 05:01 UTC, jhfnetboy approved these changes
basic fix

2021-12-26 06:37 UTC, liberhe approved these changes

2021-12-27 02:10 UTC, maroonstar commented on basic/14-chainlink-price-feed/contracts/PriceConsumerV3.sol
> +        priceFeed = AggregatorV3Interface(0x9326BFA02ADD2366b30bacB125260Af641031331);
constructor params has recovered.

2021-12-27 02:53 UTC, liberhe approved these changes

2021-12-27 10:18 UTC, liberhe approved these changes

2021-12-27 10:19 UTC, yingjingyang approved these changes

2021-12-27 10:26 UTC, luckyyang approved these changes

2021-12-27 10:26 UTC, merged