update README and index.js
Dapp-Learning-DAO/Dapp-Learning pull request #546
Opened 2021-12-30 19:26 UTC by MeoWu630

2021-12-31 03:08 UTC, Loverush submitted a review, later dismissed

2021-12-31 07:19 UTC, qizhou commented on basic/01-web3js-deploy/index.js
> +// Get privatekey from .env file
```suggestion
// Get privatekey from environment
```

2021-12-31 07:19 UTC, qizhou submitted a review, later dismissed

2022-01-03 13:32 UTC, liberhe requested changes

2022-01-03 13:32 UTC, liberhe commented on basic/03-web3js-erc20/README.md
> +- ERC20 接口及合约说明：https://docs.openzeppelin.com/contracts/2.x/api/token/erc20
please fix the conflict.

2022-01-03 21:05 UTC, MeoWu630 commented on basic/03-web3js-erc20/README.md
> +- ERC20 接口及合约说明：https://docs.openzeppelin.com/contracts/2.x/api/token/erc20
already fixed, sorry for that

2022-01-04 02:18 UTC, liberhe approved these changes

2022-01-04 02:20 UTC, liberhe commented
please join our discord https://discord.com/invite/gkENMS7cKz and introduce yourself.  You can also add WeChat yanyanho666 to join our developer group.

2022-01-05 01:02 UTC, yingjingyang approved these changes

2022-01-05 01:03 UTC, merged