Web3.js vs Ethers.js
Dapp-Learning-DAO/Dapp-Learning pull request #651
Opened 2022-03-16 08:14 UTC by 6gunner

我增加了一个task: `Web3.js vs Ethers.js `

起因我在学习dapp的时候，看到了有些项目里用web3, 而有些用ethers; 这两个库都是帮助我们和链上交互的，但是API又有很大不同; 我在刚学的时候有一些迷茫，也有些困惑。 好在现在已经弄清楚了。

我将我总结的内容整理了下，同时借鉴了下task1的项目，创建了个task0(因为我觉得这个很初级，放task71不太合适)；

辛苦pr审核者review了； 后续有新的总结的话，会继续更新。

2022-03-16 19:29 UTC, qizhou approved these changes
Cool!

2022-03-17 08:01 UTC, maroonstar commented
我们task是从web3.js开始的，所以如果在之前放出两个对比是不合适的，建议这部分内容挪到task05下，新建子文件夹存放。
另外请不要上传合约编译后的json文件，这个文件建议添加到task下的 `.gitignore` 中

2022-03-17 08:02 UTC, maroonstar requested changes
Please move there to task05, and add contract.json file in .gitignore

2022-03-17 11:56 UTC, yingjingyang approved these changes

2022-03-18 04:07 UTC, 6gunner commented
> Please move there to task05, and add contract.json file in .gitignore

I  have already moved them to task05/web3-vs-ethers

2022-03-18 07:27 UTC, maroonstar approved these changes
Great!

2022-03-18 07:28 UTC, maroonstar commented
Please jion our discord, and PM me!

2022-03-18 07:32 UTC, merged