add doc for yearn vault
Dapp-Learning-DAO/Dapp-Learning pull request #816
Opened 2022-08-04 07:27 UTC by yingjingyang

2022-08-06 05:34 UTC, arc0035 submitted a review, later dismissed

2022-08-08 05:02 UTC, 0x-stan submitted a review, later dismissed

2022-08-10 01:29 UTC, liberhe requested changes

2022-08-10 01:29 UTC, liberhe commented on defi/YFI/readme.md
> +向Curve的3pool稳定币矿池提供DAI流动性挖矿，赚取 CRV流动性挖矿激励和交易费用；
aave存dai，然后讲aave的LP放入curve的3pool？

2022-08-15 09:53 UTC, yingjingyang commented on defi/YFI/yearnVault/01-Vault.md
> +5)  判断从 strategy 提取资金过程中，造成的 totalloss 在 ( totalloss + value ) 中的占比是否小于用户传入的 maxLoss。如果大于，则说明此次的提取操作造成了过大的损失，则放弃提取；否则，提取资金
fixed

2022-08-15 09:53 UTC, yingjingyang commented on defi/YFI/readme.md
> +向Curve的3pool稳定币矿池提供DAI流动性挖矿，赚取 CRV流动性挖矿激励和交易费用；
fixed

2022-08-16 02:25 UTC, arc0035 approved these changes

2022-08-22 10:04 UTC, 0x-stan approved these changes

2022-08-24 01:30 UTC, liberhe approved these changes

2022-08-24 01:30 UTC, merged