add basic task 76 - cookbook
Dapp-Learning-DAO/Dapp-Learning pull request #844
Opened 2022-09-27 20:08 UTC by JamJomJim

Added a link to cookbook - a website that lets users quickly download source code, or deploy dozens of audited smart contracts.

Learners can use this resource to look through the most common contracts, and can quickly deploy them so that they can see the code working in action on testnet or mainnet. Being able to directly interact with a live contract helps people learn a lot faster.

2022-09-28 11:00 UTC, arc0035 approved these changes

2022-09-30 03:57 UTC, liberhe approved these changes

2022-09-30 04:07 UTC, liberhe requested changes
It looks like a tool, you can add to the tool recommendation.

2022-09-30 04:21 UTC, JamJomJim commented
Just moved this to the recommended tools section. Thanks for feedback

2022-09-30 06:16 UTC, liberhe commented
> Just moved this to the recommended tools section. Thanks for feedback

Thanks for your contribution, please add WeChat yanyanho666 to join our group.

2022-09-30 06:17 UTC, liberhe approved these changes

2022-10-04 09:31 UTC, arc0035 approved these changes

2022-10-04 10:06 UTC, merged