Process 0x task
Dapp-Learning-DAO/Dapp-Learning pull request #903
Opened 2022-12-10 05:28 UTC by liberhe

2022-12-13 03:16 UTC, arc0035 requested changes
哥，是Groth16, 拼错了

2022-12-20 10:28 UTC, liberhe commented
> 哥，是Groth16, 拼错了

fixed

2022-12-21 02:35 UTC, yingjingyang approved these changes

2022-12-21 02:40 UTC, arc0035 approved these changes

2022-12-21 02:41 UTC, merged